// <auto-generated />
using System;
using FamilyHub.Modules.MealPlan.Plan;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FamilyHub.Modules.MealPlan.Plan.Migrations
{
    [DbContext(typeof(MealPlanDbContext))]
    [Migration("20261002071938_ShoppingList")]
    partial class ShoppingList
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("FamilyHub.Modules.MealPlan.Plan.DinnerEntity", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Course")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Date", "Course");

                    b.ToTable("Dinners", (string)null);
                });

            modelBuilder.Entity("FamilyHub.Modules.MealPlan.Plan.FixedItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("Week")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Week");

                    b.ToTable("FixedItems", (string)null);
                });

            modelBuilder.Entity("FamilyHub.Modules.MealPlan.Plan.GroceryRuleEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsStaple")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mode")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PackMeasure")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PackSizes")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Section")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("GroceryRules", (string)null);
                });

            modelBuilder.Entity("FamilyHub.Modules.MealPlan.Plan.ShoppingMarkEntity", b =>
                {
                    b.Property<DateOnly>("Week")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Marks")
                        .HasColumnType("INTEGER");

                    b.HasKey("Week", "Key");

                    b.ToTable("ShoppingMarks", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
